# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EMSUpdate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EMSUpdate.proto',
  package='MpptMsgs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x45MSUpdate.proto\x12\x08MpptMsgs\"=\n\tEMSUpdate\x12\x0f\n\x07TimeTag\x18\x01 \x01(\x06\x12\x0c\n\x04load\x18\x02 \x01(\t\x12\x11\n\tLoadValue\x18\x03 \x01(\x06\x62\x06proto3'
)




_EMSUPDATE = _descriptor.Descriptor(
  name='EMSUpdate',
  full_name='MpptMsgs.EMSUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TimeTag', full_name='MpptMsgs.EMSUpdate.TimeTag', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load', full_name='MpptMsgs.EMSUpdate.load', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LoadValue', full_name='MpptMsgs.EMSUpdate.LoadValue', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['EMSUpdate'] = _EMSUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EMSUpdate = _reflection.GeneratedProtocolMessageType('EMSUpdate', (_message.Message,), {
  'DESCRIPTOR' : _EMSUPDATE,
  '__module__' : 'EMSUpdate_pb2'
  # @@protoc_insertion_point(class_scope:MpptMsgs.EMSUpdate)
  })
_sym_db.RegisterMessage(EMSUpdate)


# @@protoc_insertion_point(module_scope)
