# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EmergencyMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EmergencyMsg.proto',
  package='MpptMsgs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x45mergencyMsg.proto\x12\x08MpptMsgs\"K\n\x11\x45mergencyShutdown\x12\x0f\n\x07TimeTag\x18\x01 \x01(\x06\x12\x14\n\x0c\x65mergencyMsg\x18\x02 \x01(\t\x12\x0f\n\x07problem\x18\x03 \x01(\tb\x06proto3'
)




_EMERGENCYSHUTDOWN = _descriptor.Descriptor(
  name='EmergencyShutdown',
  full_name='MpptMsgs.EmergencyShutdown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TimeTag', full_name='MpptMsgs.EmergencyShutdown.TimeTag', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emergencyMsg', full_name='MpptMsgs.EmergencyShutdown.emergencyMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='problem', full_name='MpptMsgs.EmergencyShutdown.problem', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['EmergencyShutdown'] = _EMERGENCYSHUTDOWN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmergencyShutdown = _reflection.GeneratedProtocolMessageType('EmergencyShutdown', (_message.Message,), {
  'DESCRIPTOR' : _EMERGENCYSHUTDOWN,
  '__module__' : 'EmergencyMsg_pb2'
  # @@protoc_insertion_point(class_scope:MpptMsgs.EmergencyShutdown)
  })
_sym_db.RegisterMessage(EmergencyShutdown)


# @@protoc_insertion_point(module_scope)
