# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UpdateRequestMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UpdateRequestMsg.proto',
  package='MpptMsgs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16UpdateRequestMsg.proto\x12\x08MpptMsgs\"1\n\rUpdateRequest\x12\x0f\n\x07TimeTag\x18\x01 \x01(\x06\x12\x0f\n\x07request\x18\x02 \x01(\tb\x06proto3'
)




_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='MpptMsgs.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TimeTag', full_name='MpptMsgs.UpdateRequest.TimeTag', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='MpptMsgs.UpdateRequest.request', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'UpdateRequestMsg_pb2'
  # @@protoc_insertion_point(class_scope:MpptMsgs.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)


# @@protoc_insertion_point(module_scope)
